nz: 128
t_his: 25
t_pred: 100
lambda_v: 1000
beta: 0.1
vae_specs:
  rnn_type: gru
  x_birnn: false
  e_birnn: false
  use_drnn_mlp: true
vae_lr: 1.e-3
batch_size: 64
num_vae_epoch: 500
num_vae_epoch_fix: 100
num_vae_data_sample: 5000

#following are the  MAE training parameters

mask_ratio_min: 0.7
grad_clip: 3.0
attn_dropout: 0.1
proj_dropout: 0.1
buffer_size: 64

diffloss_d: 12
diffloss_w: 1536
num_sampling_steps: "100"
diffusion_batch_mul: 1
temperature: 1.0

weight_decay: 0.02
grad_checkpointing: false
lr: null
blr: 0.001
min_lr: 0.0
lr_schedule: constant
warmup_epochs: 100
ema_rate: 0.9999